services:
  db:
    container_name: ether-db
    image: kartoza/postgis
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_DRIVER: ${POSTGRES_DRIVER}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - 5432

  api:
    container_name: ether-api
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      # Add other environment variables here
    depends_on:
      - db

volumes:
  db_data:
