"""adding is local to message

Revision ID: 89c5f4906b55
Revises: fc5c158e9db3
Create Date: 2025-02-16 01:51:12.820088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '89c5f4906b55'
down_revision: Union[str, None] = 'fc5c158e9db3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('is_local', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'is_local')
    # ### end Alembic commands ###