"""add address to message

Revision ID: fc5c158e9db3
Revises: 54700881adbe
Create Date: 2024-12-25 22:48:38.174823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fc5c158e9db3'
down_revision: Union[str, None] = '54700881adbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('message', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'address')
    # ### end Alembic commands ###